name: Publish PowerShell Module
on:
  release:
    types:
      - created

jobs:
  build-psake:
    name: PSAke Build Process
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Dependencies from PSGallery
        shell: pwsh
        run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module Psake
            Install-Module BuildHelpers
      - name: Invoke PSAke
        shell: pwsh
        env:
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
        run: Invoke-psake -taskList 'Publish'
